services:
  postgres:
    image: postgres:17.6-alpine3.22
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techchallenge2

  tech-challenge2:
    image: tech-challenge2:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      postgres:
        condition: service_started
